# Generated by Django 5.0.2 on 2024-02-22 09:06

import django.db.models.deletion
import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('identity', models.UUIDField(db_comment='primary_key', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_comment='名称', max_length=100, unique=True, verbose_name='名称')),
                ('purchase_price', models.DecimalField(blank=True, db_comment='进价(元)', decimal_places=1, max_digits=4, null=True, verbose_name='进价(元)')),
                ('price', models.DecimalField(db_comment='单价(元)', decimal_places=1, max_digits=4, verbose_name='单价(元)')),
                ('unit', models.CharField(choices=[('个', '个'), ('袋', '袋'), ('瓶', '瓶'), ('本', '本'), ('把', '把'), ('件', '件'), ('匝', '匝'), ('条', '条'), ('支', '支'), ('根', '根'), ('桶', '桶'), ('捆', '捆'), ('盒', '盒'), ('箱', '箱'), ('米', '米'), ('斤', '斤'), ('两', '两')], db_comment='单位', max_length=5, verbose_name='单位')),
                ('manufacture_date', models.DateField(blank=True, db_comment='生产日期', null=True, verbose_name='生产日期')),
                ('shelf_life', models.SmallIntegerField(blank=True, db_comment='保质期', null=True, verbose_name='保质期单位')),
                ('shelf_life_unit', models.CharField(blank=True, choices=[('月', '月'), ('天', '天')], db_comment='保质期单位', max_length=2, null=True)),
                ('expire_date', models.DateField(blank=True, db_comment='过期日期', null=True, verbose_name='过期日期')),
                ('picture', models.ImageField(blank=True, db_comment='图片', null=True, upload_to=products.models.picture_upload_dir, verbose_name='图片')),
                ('thumnail', models.ImageField(blank=True, db_comment='小图片', null=True, upload_to=products.models.thumnail_upload_dir, verbose_name='图片')),
                ('remark', models.CharField(blank=True, db_comment='备注', max_length=200, null=True, verbose_name='备注')),
                ('catagory', models.ForeignKey(db_comment='类别', on_delete=django.db.models.deletion.CASCADE, to='products.catagory', verbose_name='类别')),
            ],
        ),
    ]
